[tool.poetry]
name = "anydoor"
version = "0.1.0"
description = "Anydoor to any cozy functions and classes. Suitable for data and llm"
authors = ["veinkr <yhf2lj@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.2"
numpy = "^1.26.4"
SQLAlchemy = "^2.0.29"
psycopg2-binary = "^2.9.9"
cryptography = "^42.0.5"
langchain = "^0.1.16"
langchain-openai = "^0.1.3"
fastapi = "^0.110.1"
cleo = "^2.1.0"

[tool.poetry.group.dev.dependencies]
tqdm = "^4.66.2"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
anydoor = "anydoor.utils.secret:Secret.generate"
