[tool.poetry]
name = "anydoor"
version = "0.1.3"
description = "Anydoor to any cozy functions and classes. Suitable for data and llm"
authors = ["veinkr <yhf2lj@gmail.com>"]
readme = "README.md"
include = [{ path = "tests", format = "sdist" }]
homepage = "https://github.com/veinkr/Anydoor"
repository = "https://github.com/veinkr/Anydoor"
documentation = "https://github.com/veinkr/Anydoor/blob/main/README.md"
keywords = ["anydoor"]

[tool.poetry.urls]
Changelog = "https://github.com/veinkr/Anydoor/commits/main/"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.2.2"
numpy = "^1.26.4"
SQLAlchemy = ">2.0"
psycopg2-binary = "^2.9.9"
cryptography = "^42.0.5"
langchain = "^0.1.16"
langchain-openai = "^0.1.3"
fastapi = "^0.110.1"
cleo = "^2.1.0"
rich = "^13.7.1"
tenacity = "^8.2.3"
colorama = "^0.4.6"
clickhouse-sqlalchemy = "^0.3.1"
hvac = "^2.2.0"
deltalake = "^0.18.2"
polars = "^1.2.1"
prompt-toolkit = "^3.0.47"
jsonmerge = "^1.9.2"

[tool.poetry.group.dev.dependencies]
tqdm = "^4.66.2"
pytest = "^8.1.1"
pytest-xdist = "^3.6.0"
twine = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
anydoor = "anydoor.consoles.application:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
