services:
  vault:
    container_name: vault
    image: hashicorp/vault:latest
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - ./data/vault/config:/vault/config
      - ./data/vault/data:/vault/data
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/config.hcl
